### ISSUE TITLE
Q1.The id range of useradd -u [id] is not restricted by UID_MIN and UID_MAX  Q2.Use "useradd -o" to create a user whose uid is 0

### ISSUE THREAD

**Issue by zhengxiaoxiaoGithub** [shadow-maint/shadow#1081]
hi,
In my tests, I found that "useradd -u" can create any number with a uid less than 4294967294, regardless of UID_MIN and UID_MAX.
Is this normal designs or bugs?
![image](https://github.com/user-attachments/assets/575612b7-7f5e-4241-9b3e-c63827cd2239)
And I can also use "useradd -o" to create a user whose uid is 0. Is this insecure?
![image](https://github.com/user-attachments/assets/4533bd13-b311-4956-a685-5b9f93a17678)

**Comment by alejandro-colomar** [comment]
> hi, In my tests, I found that "useradd -u" can create any number with a uid less than 4294967294, regardless of UID_MIN and UID_MAX. Is this normal designs or bugs? ![image](https://private-user-images.githubusercontent.com/113653702/369820441-575612b7-7f5e-4241-9b3e-c63827cd2239.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MDU3MDIsIm5iZiI6MTcyNzYwNTQwMiwicGF0aCI6Ii8xMTM2NTM3MDIvMzY5ODIwNDQxLTU3NTYxMmI3LTdmNWUtNDI0MS05YjNlLWM2MzgyN2NkMjIzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQxMDIzMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGQ1NGM5ODkwMWNhMzU0MzZiOTE0MTVkZWI3YzY3YjQxY2Q5ODUyN2UzZDFiYWQwMzViMThjMzU3OTFiNzIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qYAxcBAz-XR-CzJLkuvkj_-ttLU1Ja0mlgJ36dMoMkA)

It seems to be deliberate.  While there are checks, they only produce a warning, and not an error:

```c
$ grepc check_uid_range .
./src/useradd.c:static void check_uid_range(int rflg, uid_t user_id);
./src/useradd.c:static void check_uid_range(int rflg, uid_t user_id)
{
	uid_t uid_min ;
	uid_t uid_max ;
	if (rflg) {
		uid_max = getdef_ulong("SYS_UID_MAX",getdef_ulong("UID_MIN",1000UL)-1);
		if (user_id > uid_max) {
			fprintf(stderr, _("%s warning: %s's uid %d is greater than SYS_UID_MAX %d\n"), Prog, user_name, user_id, uid_max);
		}
	}else{
		uid_min = getdef_ulong("UID_MIN", 1000UL);
		uid_max = getdef_ulong("UID_MAX", 6000UL);
		if (uid_min <= uid_max) {
			if (user_id < uid_min || user_id >uid_max)
				fprintf(stderr, _("%s warning: %s's uid %d outside of the UID_MIN %d and UID_MAX %d range.\n"), Prog, user_name, user_id, uid_min, uid_max);
		}
	}

}
```

It was added in 00e629c0ba4b3e90b61df6dd220e5b56e2159284 in <https://github.com/shadow-maint/shadow/pull/243>.

```
commit 00e629c0ba4b3e90b61df6dd220e5b56e2159284
Author: blueskycs2c <lili.ding@cs2c.com>
Date:   Sat Apr 11 22:45:54 2020 +0800

    print a warning from useradd if -u is used with uid number outside range.

```

Maybe we could promote that to an error, I don't know.  @hallyn ?  @blueskycs2c?

And I can also use "useradd -o" to create a user whose uid is 0. Is this insecure? ![image](https://private-user-images.githubusercontent.com/113653702/369850474-4533bd13-b311-4956-a685-5b9f93a17678.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MDU3MDIsIm5iZiI6MTcyNzYwNTQwMiwicGF0aCI6Ii8xMTM2NTM3MDIvMzY5ODUwNDc0LTQ1MzNiZDEzLWIzMTEtNDk1Ni1hNjg1LTViOWY5M2ExNzY3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQxMDIzMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjRlMjg0ZDY1NDk0MTg0ODNmMDU2YTA0YjQwMGIwNDA1MzUxZjA0YzFkNTVkMTc2YTEwNWMyZmFjOTFkNGM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OT0ZA6ww1vZMbMKqCZWHVVgkJWVLpNzm2sJnOYPm9Tw)

Well, you're saying that that user is effectively root.  I'd say it can be a security problem, if the login is weak.  It can also be a security risk, if an attacker tricks a sysadmin to believe that a command is harmless because it's being run as a non-root user when it's actually root.  Don't do that?  I mean, if you don't create a second root user, it won't be a problem.  :)

**Comment by hallyn** [comment]
UID_MIN and UID_MAX are to guide the auto-selection of uids.  Not to limit what admin can do by hand.  If admin wants to specify a # outside of those, that's fine.

Thanks for checking.
