### ISSUE TITLE
shadow-4.9 does not create /etc/defailt/useradd during install

### ISSUE THREAD

**Issue by bdubbs** [shadow-maint/shadow#390]
On a new system /etc/default/useradd is not created during install.
It is a change in behavior from the previous version of shadow.

Indeed /etc/default is not created if necessary and 
'useradd -D -b /usr/bin/bash' fails with the message  'useradd: cannot create new defaults file''

This is easy enough to fix by manually creating the directory, and running the above command, but shouldn't be needed.

**Comment by hallyn** [comment]
Indeed, I guess that would be due to:

commit bbf4b79bc49fd1826eb41f6629669ef0b647267b
Author: Ludwig Nussel <ludwig.nussel@suse.de>
Date:   Thu Dec 3 18:05:59 2020 +0100

    useradd: use built-in settings by default

    Avoids installing inconsistent settings. The correct ones would be
    written as soon as an admin uses useradd -D to modify the defaults.

So the argument in that commit is that since there are defaults in the code, writing out a file is either redundant or inconsistent.

I'll post a patch to fix the fact that useradd -D is not doing mkdir of /etc/default.
