### ISSUE TITLE
 pwconv: keeps some lines that should be deleted from /etc/shadow

### ISSUE THREAD

**Issue by rbalint** [shadow-maint/shadow#60]
Copied from: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=801981

Hi, I observed a strange behaviour when pwconv should delete several
lines from /etc/shadow.

Here is how to reproduce it:

Starting from a standard installation, add some users, for example:

`  root@debian:~# for i in $(seq 10); do adduser --no-create-home --disabled-password --gecos '' test$i; done`

As expected, they appear in /etc/passwd and /etc/shadow.
Now delete them from /etc/passwd, e.g using vipw.
They are still in /etc/shadow, pwconv should be able to fix that.
However, every other entry will be kept:

```
  root@debian:~# pwconv
  root@debian:~# grep test /etc/shadow
  test2:*:16724:0:99999:7:::
  test4:*:16724:0:99999:7:::
  test6:*:16724:0:99999:7:::
  test8:*:16724:0:99999:7:::
  test10:*:16724:0:99999:7:::
```

Even more strange, after a second pwconv only test8 remains.

The same thing happens with grpconv.

**Comment by hallyn** [comment]
Oh it's actually a pretty simple cause - each time we see a spw_entry which has no pw_entry, we call commonio_remove(), which sets the shadow db cursor to the next entry (since it deletes the current one);  then we get to the top of the loop where we do spw = spw_next().
I'll push a patch to fix this, thanks for reporting it.
