### ISSUE TITLE
Y2038: utmp, utmpx and lastlog problem

### ISSUE THREAD

**Issue by ikerexxe** [shadow-maint/shadow#674]
The previous structures use `int32_t` instead of `time_t` to define its members, which will overflow them in Y2038. Anything that uses `utmp.h`, `utmpx.h`, `lastlog.h`, accesses [/run/utmp](https://manpages.opensuse.org/utmp.5), [/var/log/wtmp](https://manpages.opensuse.org/wtmp.5), [/var/log/btmp](https://manpages.opensuse.org/lastb.1) or uses the corresponding functions from glibc is affected. This project needs to move away from them. One of the solutions would be to logind instead.

This is just an informative note, and a placeholder for future work. It doesn't contain all the relevant information, for that please check [Thorsten Kukuk's note](https://github.com/thkukuk/utmpx/blob/main/Y2038.md).

**Comment by thkukuk** [comment]
I looked at the source a little bit and at least reading from systemd-logind instead of utmp should be simple:
* limits.c/check_logins(): can be replaced with sd_get_sessions() and sd_session_get_user_name(). Requires systemd >= 254 (or current git)
* logoutd.c: utmp can also be replaced with sd_get_sessions() and sd_session_get_tty().
* login.c: I would keep writing utmp for now, but change reading from it.

Replacing the functionality is possible and shouldn't be a bigger efford, but may require bigger code refactors for functions using utmp as argument.

**Comment by hallyn** [comment]
My general static linking desires probably don't apply here; I mainly need it for running in mostly empty containers.

However, this is a ...  venerable project, and it would feel like the height of hubris for me to tell users how they can and can't use it.

@thkukuk  thank you very much for all the thought you've put into this.  I will think about it more over the next few weeks.

**Comment by thkukuk** [comment]
> My general static linking desires probably don't apply here; I mainly need it for running in mostly empty containers.

Isn't busybox used for this normally? At least the majority of my running containers is using busybox, either compiled against glibc or musl libc, and the real service as single binary.

I quickly checked the glibc base containers of the three big distros (Debian, Feodra, openSUSE) and they all contain libsystemd, because it is already used by many low level projects (util-linux, procps, ...).

And we speak here about three tools:
- login - which is not useable in a container and doesn't make sense
- logoutd - which is not useable in a container and doesn't make sense.
-  su - important for a container, but the current utmp support of su does not work in a container, since there is no utmp inside a container. I'm even in the opinion, that you could drop this "counting of logged in uses", because with the current utmp design, the number is very often wrong. xterm creates fake utmp records, GNOME does not. screen creates fake utmp entries, tmux does not. So if I use xterm, I'm logged in more than once, if I use the GNOME terminal, I'm only logged in once. Which is now correct?

So for a container you don't need the first two and for su, if you disable libsystemd support for your container, you will not loose any functionality.
And: all containers contian only a stripped down version of shadow because they need useradd. useradd has no utmp support and does not need it. So I don't see any issues with your mostly empty container use-case.

**Comment by ac000** [comment]
> So if I use xterm, I'm logged in more than once, if I use the GNOME terminal, I'm only logged in once. Which is now correct?

I switched from gnome-terminal to xterm precisely because at some point gnome-terminal stopped writing utmp entries. I use `w` often to quickly see what's running in my terminals.

**Comment by ikerexxe** [comment]
# Investigation

In this investigation I'll try to go deeper into the dependencies that shadow-utils has with respect to the interfaces affected by the Y2038 glibc problem.

## utmp/utmpx/wtmp/btmp

* login: reads and writes utmp/wtmp data. The reading is done to ensure that the user has an open session by calling `get_current_utmp()`. It also makes sure that the user has not exceeded the maximum number of logins by calling `setup_limits()`. The writing is done to create or update the utmp entry by calling `setutmp()`. It also logs the login failures by calling `failtmp()`. Finally, it uses the utmp structure to define the maximum length for the username when using the `USER_NAME_MAX_LENGTH` macro.
* logoutd: reads the utmp file to check if a user is allowed to login, and, once logged in, whether the user can remain logged in.
* su: reads utmp data to ensure that the user has not exceeded the maximum number of logins by calling `setup_limits()`.

* newusers: It uses the utmp structure to define the maximum length for the username when calling `is_valid_user_name()`.
* pwck: It uses the utmp structure to define the maximum length for the username when calling `is_valid_user_name()`.
* useradd: It uses the utmp structure to define the maximum length for the username when calling `is_valid_user_name()`.
* usermod: It uses the utmp structure to define the maximum length for the username when calling `is_valid_user_name()`.

* usermod.8.xml: lost reference to utmp.

## lastlog

* lastlog: prints the content of the lastlog database.

* login: when PAM isn't used it logs the lastlog data in the database by calling `dolastlog()`.
* useradd: add the user to the lastlog database by calling `lastlog_reset()`.
* usermod: update the lastlog database when changing the UID by calling `update_lastlog()`.

# Solutions

There are too many tools and packages using the {u,w,b}tmp and lastlog interfaces, and all of them need to change from the old interfaces to the new ones at the same time. Other options would break some functionality related to these interfaces at some point or the other. That's why we need to provide distribution maintainers with a way to make changes smoothly.

## utmp/utmpx/wtmp/btmp

All the utmp function dependencies should be replaced by systemd-logind, but this needs to be done with care. That is why I propose to create a configuration option to control these changes (i.e. `SESSION_MANAGEMENT`=`UTMP` or `LOGIND`). The default value should be `UTMP`, to avoid any break. An abstraction layer should be implemented to keep both implementations at the same time, and gradually include the calls to the `logind` layer from the existing code.

Regarding the username length, [POSIX doesn't define a maximum value](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_437). To avoid any break I'd recommend following the current definition of utmp, which hardcodes the value to 32.

Finally, there's a lost reference to utmp in usermod's man page that should be removed.

## lastlog

A new configuration option should be provided to select which lastlog implementation will be provided (i.e. `LASTLOG`=`INTERNAL` or `EXTERNAL`). The default value should be `INTERNAL`. Again, an abstraction layer should be implemented to keep both implementations at the same time. When setting the `EXTERNAL` value, we should stop building the lastlog binary, and liblastlog should be used to write any change to the lastlog database.

# Questions

1. Can we deprecate (and then remove) logoutd? It doesn't seem to be provided by any major distribution.

**Comment by thkukuk** [comment]
@ikerexxe Some comments:
* `setup_limits()` for login and su: do you mean `check_logins`? Using utmp for this is not reliable, as e.g. xterm writes utmp entries, but e.g. gnome-terminal does not. Same for many other tools. Counting logind sessions is much more reliable and this is what we do now with Linux-PAM and procps-ng for this case.
* lastlog: util-linux developers discuss merging [lastlog2](https://github.com/thkukuk/lastlog2) into util-linux as lastlog replacement: [lslogins: Add support for lastlog2](https://github.com/util-linux/util-linux/pull/2164#issuecomment-1580331283)
* Regarding the username length: the feedback I got on lwn.net and otherwise is, that people would like to see this restriction removed. Maybe a configure option in login.defs?
* logoutd: wouldn't this be something which should be part of systemd-logind? If they don't have already something in this regard.
* Priority of logind vs. utmp: procps-ng and util-linux maintainers decided that they want to use logind if available, else do a fallback to utmp
* wtmp: for openSUSE and further SUSE products we decided to switch to [wtmpdb](https://github.com/thkukuk/wtmpdb), since this comes with a PAM module, we don't need to touch any application. And we will stop writing wtmp entries over the time.

**Comment by ikerexxe** [comment]
>     * `setup_limits()` for login and su: do you mean `check_logins`? Using utmp for this is not reliable, as e.g. xterm writes utmp entries, but e.g. gnome-terminal does not. Same for many other tools. Counting logind sessions is much more reliable and this is what we do now with Linux-PAM and procps-ng for this case.

I was referencing to the high-level call, `setup_limits()`, because at some point it calls `check_logins()`. So, yes, we are referring to the same thing.

Reliable or not, some users might be depending on its behaviour, so we can't remove it altogether. Some type of backward compatibility is still needed for those distributions that want to keep using the old interface.

By the way, do all the tools write information to logind? I guess not.

>     * lastlog: util-linux developers discuss merging [lastlog2](https://github.com/thkukuk/lastlog2) into util-linux as lastlog replacement: [lslogins: Add support for lastlog2](https://github.com/util-linux/util-linux/pull/2164#issuecomment-1580331283)

Good news! That will improve the maintenance.

>     * Regarding the username length: the feedback I got on lwn.net and otherwise is, that people would like to see this restriction removed. Maybe a configure option in login.defs?

I proposed to hardcode it because I think it's the easier way, but I agree that if you received feedback to change it then we should follow it. In this case, I propose to use the `sysconf(_SC_LOGIN_NAME_MAX)` interface provided by the kernel. Let's be honest, we can't allow a bigger username if the kernel won't support it.

Source: https://systemd.io/USER_NAMES/

>     * logoutd: wouldn't this be something which should be part of systemd-logind? If they don't have already something in this regard.

I have the same understanding, and AFAIK logoutd isn't provided by any major distribution. That's why I'd like to first deprecate it, and then, remove it.

>     * Priority of logind vs. utmp: procps-ng and util-linux maintainers decided that they want to use logind if available, else do a fallback to utmp

Not a problem, we could also follow their approach and prioritize logind over utmp. However, I'd like to maintain backward compatibility.

>     * wtmp: for openSUSE and further SUSE products we decided to switch to [wtmpdb](https://github.com/thkukuk/wtmpdb), since this comes with a PAM module, we don't need to touch any application. And we will stop writing wtmp entries over the time.

That would also be my final objective, but we still need to provide backward compatibility.

**Comment by thkukuk** [comment]
> By the way, do all the tools write information to logind? I guess not.

No tool writes directly to logind, this is all done via PAM modules. We have:
* pam_systemd
* pam_wtmpdb
* pam_lastlog2

This allows a consistent collection of data and you only need to adjust one piece of code, and not many applications.
Exception is sshd, due to the sshd design, sshd need to report some missing data later via DBUS. But this API will also be only available with systemd v254 and later.

**Comment by hallyn** [comment]
> You are welcome. @hallyn do you agree with the outcomes?

Still reading, but it sounds good.

The general idea of making the new code available asap but leaving the fallback available for several years is the responsible path.

> What do you think about deprecating (and later on) removing logoutd?

I think that's good.  If when we deprecate it someone tells us they are relying on it, we can reconsider then.

**Comment by ikerexxe** [comment]
I have written a [blog post](https://ikerexxe.github.io/idm/2023/06/14/Y2038-problem-in-shadow.html) on this topic with all comments in mind. Thank you for your help!

I plan to work on fixing the issues in the following weeks.

**Comment by ikerexxe** [comment]
There's still some work to do here, so I'm reopening the issue
