### ISSUE TITLE
`./share/containers/fedora.dockerfile` doesn't build

### ISSUE THREAD

**Issue by alejandro-colomar** [shadow-maint/shadow#839]
```sh
$ sudo docker build -f ./share/containers/fedora.dockerfile .
[...]
checking for library containing readpassphrase... no
configure: error: readpassphrase() is missing, either from libc or libbsd
The command '/bin/sh -c ./autogen.sh --enable-shadowgrp --enable-man --with-audit         --with-sha-crypt --with-bcrypt --with-yescrypt --with-selinux         --without-libcrack --without-libpam --enable-shared         --with-group-name-max-length=32 --enable-lastlog --enable-logind=no' returned a non-zero code: 1
```

That is on the `master` branch.

I removed all the cached images from docker so that it starts from scratch, and I still see the failure.  Also, CI started failing for a PR that doesn't touch anything related to readpassphrase(3bsd) or libbsd.

**Comment by ikerexxe** [comment]
It's failing because the latest stable Fedora has been switched to 39 recently, and this one doesn't containe libbsd dependency.

**Comment by alejandro-colomar** [comment]
But Fedora 39 still has libbsd, right?  I see it in this page: <https://packages.fedoraproject.org/pkgs/libbsd/libbsd/>

Did they remove it from the docker container or something?

**Comment by ikerexxe** [comment]
Yes, libbsd is still there but it's [not recommended](https://github.com/minimization/content-resolver-input/blob/95d4087bdf7a78a0b026d753e5c4b3b22b0df7ce/configs/sst_pt_gcc-unwanted.yaml#L51) to link base packages against libbsd.

The package is available for download, but it has to be installed manually, or via a dependency. I dropped the shadow dependency for this package some time ago for Fedora 39+, but I forgot to update the build configuration options.

Last week Fedora 39 was released and I guess at some point during this time the containers tag for `stable` was updated from 38 to 39. That's why we can see the error now, and not before.

**Comment by alejandro-colomar** [comment]
I think we should be prefer linking against libbsd:

-  Our programs are not threaded, so being MT-Unsafe (Multi-Thread Unsafe) is not a bug here.
-  We already made sure we don't use libbsd's arc4random(3bsd): <https://github.com/shadow-maint/shadow/commit/ac8b81c2b7ed378528e5cc60754e10be1e369e40>
-  We don't use functions that are incompatible with glibc (fgetln, setproctitle).

A problem of not linking to libbsd is that we use our own definition of readpassphrase(3bsd).  Usually, I'd say it's fine to dog-food our own definitions of stuff, but that function scares me, at 141 lines of sensitive code.

**Comment by ikerexxe** [comment]
> I think we should prefer linking against libbsd:

I also prefer it, but shadow is included in the base image, and thus having libbsd as a dependency also makes this package part of the base image. This last part wants to be avoided by Fedora.
