### ISSUE TITLE
Chage miscalculation

### ISSUE THREAD

**Issue by jubalh** [shadow-maint/shadow#939]
We noticed something strange on our openSUSE systems. Unfortunately I didn't yet have the time to look into it.
Maybe it's best that I open this upstream bug in case it's a wider problem which we might want to fix before the next stable release.

```
# date
Tue Sep  1 14:16:35 CEST 2020
# chage -d today joesix
# chage -l joesix
Last password change                                    : Sep 02, 2020
[...]
# chage -d yesterday joesix
# chage -l joesix
Last password change                                    : Sep 02, 2020
[...]
# chage -d "2 days ago" joesix
# chage -l joesix
Last password change                                    : Aug 31, 2020
[...]
```

```
# date
Wed Sep  2 13:57:31 CEST 2020

# chage -l joesix
Last password change					: Sep 02, 2020

# date
Wed Sep  2 14:05:21 CEST 2020

# chage -d 'today' joesix
# chage -l joesix
Last password change					: Sep 03, 2020
```

Maybe rollover is at 12:00:00 UTC?

**Comment by alejandro-colomar** [comment]
While not related, I'd like to investigate this issue after merging

-  <https://github.com/shadow-maint/shadow/pull/876>

since it significantly simplifies code handling dates, and so it will be easier to inspect after that change.

**Comment by alejandro-colomar** [comment]
This code seems to match the 12:00 UTC thingy:

```c
$ grepc strtoday . | tail
		return retdate;
	}

	t = get_date (str, NULL);
	if ((time_t) - 1 == t) {
		return -2;
	}
	/* convert seconds to days since 1970-01-01 */
	return (t + DAY / 2) / DAY;
}
```

I don't get why it adds that half day.  :|

**Comment by alejandro-colomar** [comment]
In the long term, I think we should move away from `lib/getdate.y`.  I suspect it was written in a time when getdate(3) might not be portable enough.

To-day, using POSIX.1-2008, we can just `day = mktime(getdate(string)) / DAY;` and call it a day.  And we would benefit of any bug fixes that libc applies to those functions, instead of the monster we have in `lib/getdate.y`, which I don't think is maintainable.

**Comment by hallyn** [comment]
@jubalh could you verify whether master now fixes these?

**Comment by alejandro-colomar** [comment]
> In the long term, I think we should move away from `lib/getdate.y`. I suspect it was written in a time when getdate(3) might not be portable enough.
> 
> To-day, using POSIX.1-2008, we can just `day = mktime(getdate(string)) / DAY;` and call it a day. And we would benefit of any bug fixes that libc applies to those functions, instead of the monster we have in `lib/getdate.y`, which I don't think is maintainable.

I'll call the time doctor.  :)

Hi @eggert!

We have some very old mktime(getdate())-like implementation in shadow, called get_date(), written in YACC, and it's buggy.

I'd like to replace it by something that is easier to maintain, if possible.  But also, I'd like to not regress on what it accepts (unless we need for major reasons).

From what I can see, getdate(3), being based on strptime(3), can't interpret things like `"yesterday"`, which our get_date() accepts.

Do you know of any library function that does this?
Or failing that, is there any standard or common system `DATEMSK` file so that we can use it without having to define it ourselves?

Have a lvoely day!
Alex

**Comment by eggert** [comment]
On 2024-02-16 02:53, Alejandro Colomar wrote:
> Do you know of any library function that does this?
> Or failing that, is there any standard or common system `DATEMSK` file
> so that we can use it without having to define it ourselves?

Gnulib has a parse_datetime module, which is what GNU 'date' uses. So if 
you want to be compatible with GNU 'date' that's the way to go. It 
supports strings like "yesterday".

No date parser is perfect. They all have glitches.

**Comment by alejandro-colomar** [comment]
Hi Paul,

> On 2024-02-16 02:53, Alejandro Colomar wrote:
>> Do you know of any library function that does this? Or failing that, is there any standard or common system `DATEMSK` file so that we can use it without having to define it ourselves?

> Gnulib has a parse_datetime module, which is what GNU 'date' uses. So if you want to be compatible with GNU 'date' that's the way to go. It supports strings like "yesterday". No date parser is perfect. They all have glitches.

Thanks.  I was worried that your answer would probably be Gnulib.  :p

Since Gnulib is (L)GPL'd and this project is BSD'd, and it's a source-code library, I guess they are incompatible.  (And I would prefer a dependency that is an actual system library.)

Hmmm, I guess we need to stick to this yacc file.

Have a lovely night!
Alex
